### ISSUE TITLE
Space key shakes the screen

### ISSUE THREAD

**Issue by towerofnix** [coolandgood/game#9]
..for no reason?

**Comment by TheInitializer** [comment]
it's not a bug, it's a gold gold

**Comment by TheInitializer** [comment]
Sorry my friend grabbed my phone

**Comment by TheInitializer** [comment]
Sorry my friend grabbed my phone

**Comment by towerofnix** [comment]
@PullJosh @TheInitializer current status on this? I'm disregarding init's messages/close status (since *"my friend grabbed my phone"*) but @PullJosh added the "wontfix" label?

**Comment by PullJosh** [comment]
> @PullJosh @TheInitializer current status on this? I'm disregarding init's messages/close status (since "my friend grabbed my phone") but @PullJosh added the "wontfix" label?

Mostly as a joke. :P It's a funny random "enhancement", but should probably be removed.

**Comment by TheInitializer** [comment]
>should probably be removed.

nooo

**Comment by PullJosh** [comment]
What if this was triggered using the konami code rather than space bar?

**Comment by bates64** [comment]
Whoops, I forgot about that. Blame me - it was for screen shake testing before it was implemented 📦
